suggestorHost: localhost
suggestorPort: 8080

mockSuggestorApi: ${MOCK_SUGGESTOR_API:-false}

contentApiUrl: http://api.ft.com
contentApiAuthKey: ${CONTENT_API_AUTH_KEY}

topStoriesLists:
- 520ddb76-e43d-11e4-9e89-00144feab7de
- bf3045bc-2402-11e6-aa98-db1e01fabc0c

server:
  applicationConnectors:
    - type: http
      port: 9090

  adminConnectors:
      - type: http
        port: 9091

logging:
  level: INFO

  loggers:
    io.dropwizard: DEBUG
    com.ft.jerseyhttpwrapper.AttemptLogger: WARN

  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601, GMT}] %c: %X{transaction_id} %m [%thread]%n%xEx"
